version: '3.8'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
    command: >
      sh -c "cp -r /app/build/. /frontend_static/ && 
             npx -y http-server -p 8000 /frontend_static"
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
      - gateway
    ports:
      - 8000:8000
  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
    depends_on:
      - backend
      - db
